:project:
  :build_root: build
  :use_exceptions: FALSE
  :use_mocks: TRUE

:paths:
  :test:
    - tests/**
  :include:
    - .
    - app
    - drivers
    - platform
    - system
  :source:
    - app/**
    - drivers/**
    - platform/**
    - system/**
  :support:
    - tests/support

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :plugins:
    - :ignore
    - :callback
    - :ignore_arg
    - :expect_any_args
    - :return_thru_ptr

:flags:
  :test:
    :compile:
      '*':
        - -std=gnu2x
  :release:
    :compile:
      - -std=gnu2x
